server {
    listen 80;

    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        client_max_body_size 20M;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
